UMS/config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :relationships
  resources :users
  get '/auth/:provider/callback', to: 'sessions#create'

  root 'users#welcome'

end

UMS/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

UMS/app/models/session.rb
class Session < ActiveRecord::Base
end

UMS/app/models/user.rb
class User < ActiveRecord::Base
   has_many :relationships
   has_many :friends, :through => :relationships
  validates :email, confirmation: true, :on => :update
  validates :email_confirmation, presence: true, :on => :update
  validates :terms_of_service, acceptance: true, :on => :update

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash[:provider], uid: auth_hash[:uid]).first_or_create
    user.update(
      # name: auth_hash[:info][:nickname], --> Don't use twitter name for now.
      profile_image: auth_hash[:info][:image],
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end
end

UMS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

UMS/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @relationship = current_user.relationships.build(:friend_id => params[:friend_id])
    if @relationship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:notice] = "Unable to add friend"
      redirect_to root_url
    end
  end
end

UMS/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

UMS/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def welcome
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    binding.pry
    if @user.save
      render "show"
    else
      flash[:notice] = "Could not create user account. Make sure emails match."
      redirect_to :back
    end
  end

  def update
    @user = current_user
    @user.update(user_params) #need better error handling here - if error is not nil?
    if @user.save
      render "show"
    else
      flash[:notice] = "Could not create user account. Make sure emails match."
      render "show"
    end
  end


  def show
    @user = current_user
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :city, :country, :age, :email, :email_confirmation, :bio, :online_portfolio, :accept_terms
    )
  end

end

UMS/app/helpers/application_helper.rb
module ApplicationHelper
end

UMS/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

UMS/app/helpers/sessions_helper.rb
module SessionsHelper
end

UMS/app/helpers/users_helper.rb
module UsersHelper
end

UMS/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

UMS/app/views/users/index.html.erb
Index
<%if @users%>
  <%@users.map do |user|%>
  <div class="user">
    <%=user.name%>
    <%= link_to "Add friend", relationships_path(:friend_id => user), :method => :post %>
  </div>
  <%end%>
<%end%>

UMS/app/views/users/new.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%=form_for @user, url: {action: "create"} do |f|%>
Name: <%= f.text_field :name %><br />
City: <%= f.text_field :city %><br />
Country: <%= f.text_field :country %><br />
Age: <%= f.text_field :age %><br />
Email: <%= f.text_field :email %><br />
Email Confirmation: <%= f.text_field :email_confirmation %><br />
Bio: <%= f.text_area :age %><br />
Online Portfolio Link: <%= f.text_field :online_portfolio %><br />
Accept Terms: <%= f.check_box :terms_of_service %><br />
<%= f.submit %><br />
<%end%>
bio**
accept_terms**
email
email_confirmation

UMS/app/views/users/show.html.erb
User Profile<br>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%if @user.accept_terms %>
  <p>Welcome, <%=@user.name%></p>
  <p><%= link_to "Find friends", users_path %></p>
  <br>
  <%if @user.friends %>
    <h2>Your friends</h2>
      <ul>
        <%@user.friends.map do |friend| %>
        <li><%= @user.name %></li>
        <%end%>
      </ul>
    <%end%>
  <%end%>


<%unless @user.accept_terms%> 
Complete your profile to search for friends.
  <%=form_for @user, url: {action: "update"} do |f|%>
    Name: <%= f.text_field :name %><br />
    City: <%= f.text_field :city %><br />
    Country: <%= f.text_field :country %><br />
    Age: <%= f.text_field :age %><br />
    Email: <%= f.text_field :email %><br />
    Email Confirmation: <%= f.text_field :email_confirmation %><br />
    Bio: <%= f.text_area :bio %><br />
    Online Portfolio Link: <%= f.text_field :online_portfolio %><br />
    Accept Terms: <%= f.check_box :accept_terms %><br />
  <%= f.submit %><br />
<%end%>

<%end%>

UMS/app/views/users/welcome.html.erb
Homepage<br>
<%if current_user%>
Signed in as <%=current_user.name%>
<%= link_to "See my profile", user_path(current_user)%>
<%else%>
<%= link_to "Sign up with Twitter", '/auth/twitter'%><br>
By clicking sign up, you agree to all terms of service.
<%end%>